# Generated by Django 4.2.7 on 2023-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('O', 'Organization'), ('A', 'Admin')], max_length=1)),
                ('admin_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('O', 'Organization'), ('A', 'Admin')], max_length=1)),
                ('organization_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('O', 'Organization'), ('A', 'Admin')], max_length=1)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Resident',
            },
        ),
    ]
