# Generated by Django 4.2.7 on 2023-12-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateAccount', '0001_initial'),
        ('eveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='approve_Account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eveapp.account'),
        ),
    ]
