# Generated by Django 4.2.7 on 2023-12-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAccount', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default=models.BigAutoField(primary_key=True, serialize=False), max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(default=models.BigAutoField(primary_key=True, serialize=False), max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=models.BigAutoField(primary_key=True, serialize=False), max_length=50),
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
