# Generated by Django 4.2.7 on 2023-12-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameApplicant', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=250)),
                ('account_status', models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected')], max_length=1)),
                ('orgName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.organization')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
    ]
